name: Android Firebase Upload

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build APK (Release)
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Decode Service Account JSON
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > $HOME/service-account.json

      - name: Upload to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ci-cd-example-7bd73
          serviceCredentialsFile: $HOME/google-services.json
          groups: Test
          releaseNotes: "Uploaded via GitHub Actions"
          file: android/app/build/outputs/apk/release/app-release.apk